language: erlang
otp_release:
  - R15B01
  - R16B03
  - 17.0
script: make clean test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - scherpenisse@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_script:
  - sh -c "if [ '$DBDRIVER' = 'mysql' ]; then mysql -e 'create database persi_test;'; fi"
  - sh -c "if [ '$DBDRIVER' = 'pgsql' ]; then sleep 5; psql -c \"create user persi password ''\" -U postgres; psql -c \"create database persi_test owner = persi;\" -U postgres; fi"
env:
  - DBDRIVER=sqlite
  - DBDRIVER=mysql
  - DBDRIVER=pgsql
